config/routes.rb
Rails.application.routes.draw do
  get '/saml/auth' => 'saml_idp#new'
  post '/saml/auth' => 'saml_idp#create'
  get '/saml/metadata' => 'saml_idp#metadata'

  #
  # Manager
  #

  namespace :manager do
    resources :procedures, only: [:index, :show] do
      post 'whitelist', on: :member
      post 'draft', on: :member
      post 'discard', on: :member
      post 'restore', on: :member
      post 'add_administrateur', on: :member
      post 'change_piece_justificative_template', on: :member
      get 'export_mail_brouillons', on: :member
    end

    resources :dossiers, only: [:index, :show] do
      post 'discard', on: :member
      post 'restore', on: :member
      post 'repasser_en_instruction', on: :member
    end

    resources :administrateurs, only: [:index, :show, :new, :create] do
      post 'reinvite', on: :member
      delete 'delete', on: :member
    end

    resources :users, only: [:index, :show, :edit, :update] do
      delete 'delete', on: :member
      post 'resend_confirmation_instructions', on: :member
      put 'enable_feature', on: :member
      get 'emails', on: :member
      put 'unblock_email'
    end

    resources :instructeurs, only: [:index, :show] do
      post 'reinvite', on: :member
      delete 'delete', on: :member
    end

    resources :dossiers, only: [:show]

    resources :demandes, only: [:index]

    resources :bill_signatures, only: [:index]

    resources :services, only: [:index, :show]

    post 'demandes/create_administrateur'
    post 'demandes/refuse_administrateur'

    authenticate :super_admin do
      mount Flipper::UI.app(-> { Flipper.instance }) => "/features", as: :flipper
      match "/delayed_job" => DelayedJobWeb, :anchor => false, :via => [:get, :post]
    end

    root to: "administrateurs#index"
  end

  #
  # Letter Opener
  #

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  #
  # Monitoring
  #

  get "/ping" => "ping#index"

  #
  # Authentication
  #

  devise_for :super_admins, skip: [:registrations], controllers: {
    sessions: 'super_admins/sessions',
    passwords: 'super_admins/passwords'
  }

  devise_scope :super_admin do
    get '/super_admins/password/test_strength' => 'super_admins/passwords#test_strength'
  end

  get 'super_admins/edit_otp', to: 'super_admins#edit_otp', as: 'edit_super_admin_otp'
  put 'super_admins/enable_otp', to: 'super_admins#enable_otp', as: 'enable_super_admin_otp'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    get '/users/no_procedure' => 'users/sessions#no_procedure'
    get 'connexion-par-jeton/:id' => 'users/sessions#sign_in_by_link', as: 'sign_in_by_link'
    get 'lien-envoye/:email' => 'users/sessions#link_sent', constraints: { email: /.*/ }, as: 'link_sent'
  end

  devise_scope :administrateur do
    get '/administrateurs/password/test_strength' => 'administrateurs/passwords#test_strength'
  end

  #
  # Main routes
  #

  root 'root#index'
  get '/administration' => 'root#administration'

  get 'users' => 'users#index'
  get 'admin' => 'admin#index'

  get '/stats' => 'stats#index'
  get '/stats/download' => 'stats#download'

  namespace :france_connect do
    get 'particulier' => 'particulier#login'
    get 'particulier/callback' => 'particulier#callback'
  end

  namespace :champs do
    get ':position/siret', to: 'siret#show', as: :siret
    get ':position/dossier_link', to: 'dossier_link#show', as: :dossier_link
    post ':position/carte', to: 'carte#show', as: :carte

    get ':champ_id/carte/features', to: 'carte#index', as: :carte_features
    post ':champ_id/carte/features', to: 'carte#create'
    post ':champ_id/carte/features/import', to: 'carte#import'
    patch ':champ_id/carte/features/:id', to: 'carte#update'
    delete ':champ_id/carte/features/:id', to: 'carte#destroy'

    post ':position/repetition', to: 'repetition#show', as: :repetition
    put 'piece_justificative/:champ_id', to: 'piece_justificative#update', as: :piece_justificative
  end

  resources :attachments, only: [:show, :destroy]

  get "patron" => "root#patron"
  get "accessibilite" => "root#accessibilite"
  get "suivi" => "root#suivi"
  post "dismiss_outdated_browser" => "root#dismiss_outdated_browser"

  get "contact", to: "support#index"
  post "contact", to: "support#create"

  get "contact-admin", to: "support#admin"

  post "webhooks/helpscout", to: "webhook#helpscout"
  match "webhooks/helpscout", to: lambda { |_| [204, {}, nil] }, via: :head

  #
  # Deprecated UI
  #

  namespace :users do
    resources :dossiers, only: [] do
      post '/carte/zones' => 'carte#zones'
      get '/carte' => 'carte#show'
      post '/carte' => 'carte#save'
      post '/repousser-expiration' => 'dossiers#extend_conservation'
    end

    # Redirection of legacy "/users/dossiers" route to "/dossiers"
    get 'dossiers', to: redirect('/dossiers')
    get 'dossiers/:id/recapitulatif', to: redirect('/dossiers/%{id}')
    get 'dossiers/invites/:id', to: redirect(path: '/invites/%{id}')

    get 'activate' => '/users/activate#new'
    patch 'activate' => '/users/activate#create'
  end

  # order matters: we don't want those routes to match /admin/procedures/:id
  get 'admin/procedures/new' => 'new_administrateur/procedures#new', as: :new_admin_procedure

  namespace :admin do
    get 'activate' => '/administrateurs/activate#new'
    patch 'activate' => '/administrateurs/activate#create'
    get 'procedures/archived', to: redirect('/admin/procedures?statut=archivees')
    get 'procedures/draft', to: redirect('/admin/procedures?statut=brouillons')

    resources :procedures, only: [:destroy] do
      collection do
        get 'new_from_existing' => 'procedures#new_from_existing', as: :new_from_existing
      end

      member do
        delete :delete_logo
        delete :delete_deliberation
        delete :delete_notice
      end

      put 'archive' => 'procedures#archive', as: :archive
      get 'publish_validate' => 'procedures#publish_validate', as: :publish_validate
      put 'clone' => 'procedures#clone', as: :clone
    end

    namespace :assigns do
      get 'show' # delete after fixed tests admin/instructeurs/show_spec without this line
    end

    resources :instructeurs, only: [:index, :create, :destroy]
  end

  resources :invites, only: [:show, :destroy] do
    collection do
      post 'dossier/:dossier_id', to: 'invites#create', as: :dossier
    end
  end

  #
  # API
  #

  authenticated :user, lambda { |user| user.administrateur_id } do
    mount GraphqlPlayground::Rails::Engine, at: "/graphql", graphql_path: "/api/v2/graphql"
  end

  namespace :api do
    namespace :v1 do
      resources :procedures, only: [:index, :show] do
        resources :dossiers, only: [:index, :show]
      end
    end

    namespace :v2 do
      post :graphql, to: "graphql#execute"
      get 'dossiers/pdf/:id', format: :pdf, to: "dossiers#pdf", as: :dossier_pdf
      get 'dossiers/geojson/:id', to: "dossiers#geojson", as: :dossier_geojson
    end
  end

  #
  # User
  #

  scope module: 'users' do
    namespace :commencer do
      get '/test/:path/dossier_vide', action: 'dossier_vide_pdf_test', as: :dossier_vide_test
      get '/test/:path', action: 'commencer_test', as: :test
      get '/:path', action: 'commencer'
      get '/:path/dossier_vide', action: 'dossier_vide_pdf', as: :dossier_vide
      get '/:path/sign_in', action: 'sign_in', as: :sign_in
      get '/:path/sign_up', action: 'sign_up', as: :sign_up
      get '/:path/france_connect', action: 'france_connect', as: :france_connect
    end

    resources :dossiers, only: [:index, :show, :new] do
      member do
        get 'identite'
        patch 'update_identite'
        get 'siret'
        post 'siret', to: 'dossiers#update_siret'
        get 'etablissement'
        get 'brouillon'
        patch 'brouillon', to: 'dossiers#update_brouillon'
        get 'modifier', to: 'dossiers#modifier'
        patch 'modifier', to: 'dossiers#update'
        get 'merci'
        get 'demande'
        get 'messagerie'
        post 'commentaire' => 'dossiers#create_commentaire'
        post 'ask_deletion'
        get 'attestation'
      end

      collection do
        get 'recherche'
      end
    end
    resource :feedback, only: [:create]
    get 'demarches' => 'demarches#index'

    get 'profil' => 'profil#show'
    post 'renew-api-token' => 'profil#renew_api_token'
    # allow refresh 'renew api token' page
    get 'renew-api-token' => redirect('/profil')
    patch 'update_email' => 'profil#update_email'
  end

  #
  # Expert
  #
  scope module: 'experts', as: 'expert' do
    get 'avis', to: 'avis#index', as: 'all_avis'

    # this redirections are ephemeral, to ensure that emails sent to experts before are still valid
    # TODO : they will be removed in September, 2020
    get 'avis/:id', to: redirect('/procedures/old/avis/%{id}')
    get 'avis/:id/sign_up/email/:email', to: redirect("/procedures/old/avis/%{id}/sign_up/email/%{email}"), constraints: { email: /.*/ }

    resources :procedures, only: [], param: :procedure_id do
      member do
        resources :avis, only: [:show, :update] do
          get '', action: 'procedure', on: :collection, as: :procedure
          member do
            get 'instruction'
            get 'messagerie'
            post 'commentaire' => 'avis#create_commentaire'
            post 'avis' => 'avis#create_avis'
            get 'bilans_bdf'

            get 'sign_up/email/:email' => 'avis#sign_up', constraints: { email: /.*/ }, as: 'sign_up'
            post 'sign_up/email/:email' => 'avis#update_expert', constraints: { email: /.*/ }
          end
        end
      end
    end
  end

  #
  # Instructeur
  #

  scope module: 'instructeurs', as: 'instructeur' do
    get 'avis', to: 'avis#index', as: 'all_avis'

app/controllers/manager/administrateurs_controller.rb
module Manager
  class AdministrateursController < Manager::ApplicationController
    def create
      administrateur = current_super_admin.invite_admin(create_administrateur_params[:email])

      if administrateur.errors.empty?
        flash.notice = "Administrateur créé"
        redirect_to manager_administrateurs_path
      else
        render :new, locals: {
          page: Administrate::Page::Form.new(dashboard, administrateur)
        }
      end
    end

    def reinvite
      Administrateur.find_inactive_by_id(params[:id]).user.invite_administrateur!(current_super_admin.id)
      flash.notice = "Invitation renvoyée"
      redirect_to manager_administrateur_path(params[:id])
    end

    def delete
      administrateur = Administrateur.find(params[:id])

      administrateur.delete_and_transfer_services

      logger.info("L'administrateur #{administrateur.id} est supprimé par #{current_super_admin.id}")
      flash[:notice] = "L'administrateur #{administrateur.id} est supprimé"

      redirect_to manager_administrateurs_path
    end

    private

    def create_administrateur_params
      params.require(:administrateur).permit(:email)
    end
  end
end

app/controllers/manager/application_controller.rb
module Manager
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_super_admin!
    before_action :default_params

    def default_params
      params[resource_name] ||= {
        order: "created_at",
        direction: "desc"
      }
    end

    protected

    def authenticate_super_admin!
      if super_admin_signed_in? && current_super_admin.otp_required_for_login?
        super
      elsif super_admin_signed_in?
        redirect_to edit_super_admin_otp_path
      else
        redirect_to new_super_admin_session_path
      end
    end

    private

    # private method called by rails fwk
    # see https://github.com/roidrage/lograge
    def append_info_to_payload(payload)
      super

      payload.merge!({
        user_agent: request.user_agent,
        user_id: current_user&.id,
        user_email: current_user&.email
      }.compact)

      if browser.known?
        payload.merge!({
          browser: browser.name,
          browser_version: browser.version.to_s,
          platform: browser.platform.name
        })
      end

      payload
    end
  end
end

app/controllers/manager/bill_signatures_controller.rb
module Manager
  class BillSignaturesController < Manager::ApplicationController
  end
end

app/controllers/manager/demandes_controller.rb
module Manager
  class DemandesController < Manager::ApplicationController
    def index
      @pending_demandes = pending_demandes
    end

    def create_administrateur
      administrateur = current_super_admin.invite_admin(create_administrateur_params[:email])

      if administrateur.errors.empty?
        PipedriveAcceptsDealsJob.perform_later(
          create_administrateur_params[:person_id],
          current_super_admin.id,
          create_administrateur_params[:stage_id]
        )

        flash.notice = "Administrateur créé"
        redirect_to manager_demandes_path
      else
        flash.now.alert = administrateur.errors.full_messages.to_sentence
        @pending_demandes = pending_demandes
        render :index
      end
    end

    def refuse_administrateur
      PipedriveRefusesDealsJob.perform_later(
        refuse_administrateur_params[:person_id],
        current_super_admin.id
      )

      AdministrationMailer
        .refuse_admin(refuse_administrateur_params[:email])
        .deliver_later

      flash.notice = "La demande de #{refuse_administrateur_params[:email]} va être refusée"
      redirect_to manager_demandes_path
    end

    private

    def create_administrateur_params
      params.permit(:email, :person_id, :stage_id)
    end

    def refuse_administrateur_params
      params.permit(:email, :person_id)
    end

    def pending_demandes
      already_approved_emails = Administrateur.eager_load(:user)
        .where(users: { email: demandes.map { |d| d[:email] } })
        .map(&:email)

      demandes.reject { |demande| already_approved_emails.include?(demande[:email]) }
    end

    def demandes
      @demandes ||= PipedriveService.get_demandes
    end
  end
end

app/controllers/manager/dossiers_controller.rb
module Manager
  class DossiersController < Manager::ApplicationController
    #
    # Administrate overrides
    #

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    def scoped_resource
      if unfiltered_list?
        # Don't display discarded dossiers in the unfiltered list…
        Dossier.kept
      else
        # … but allow them to be searched and displayed.
        Dossier.with_discarded
      end
    end

    #
    # Custom actions
    #

    def discard
      dossier = Dossier.find(params[:id])
      dossier.discard_and_keep_track!(current_super_admin, :manager_request)

      logger.info("Le dossier #{dossier.id} est supprimé par #{current_super_admin.email}")
      flash[:notice] = "Le dossier #{dossier.id} a été supprimé."

      redirect_to manager_dossier_path(dossier)
    end

    def restore
      dossier = Dossier.with_discarded.find(params[:id])
      dossier.restore(current_super_admin)

      flash[:notice] = "Le dossier #{dossier.id} a été restauré."

      redirect_to manager_dossier_path(dossier)
    end

    def repasser_en_instruction
      dossier = Dossier.find(params[:id])
      dossier.repasser_en_instruction(current_super_admin)

      logger.info("Le dossier #{dossier.id} est repassé en instruction par #{current_super_admin.email}")
      flash[:notice] = "Le dossier #{dossier.id} est repassé en instruction."

      redirect_to manager_dossier_path(dossier)
    end

    private

    def unfiltered_list?
      action_name == "index" && !params[:search]
    end
  end
end

app/controllers/manager/instructeurs_controller.rb
module Manager
  class InstructeursController < Manager::ApplicationController
    def reinvite
      instructeur = Instructeur.find(params[:id])
      instructeur.user.invite!
      flash[:notice] = "Instructeur réinvité."
      redirect_to manager_instructeur_path(instructeur)
    end

    def delete
      instructeur = Instructeur.find(params[:id])

      if !instructeur.can_be_deleted?
        fail "Impossible de supprimer cet instructeur car il est administrateur ou il est le seul instructeur sur une démarche"
      end
      instructeur.destroy!

      logger.info("L'instructeur #{instructeur.id} est supprimé par #{current_super_admin.id}")
      flash[:notice] = "L'instructeur #{instructeur.id} est supprimé"

      redirect_to manager_instructeurs_path
    end
  end
end

app/controllers/manager/services_controller.rb
module Manager
  class ServicesController < Manager::ApplicationController
  end
end

app/controllers/users/demarches_controller.rb
module Users
  class DemarchesController < UserController
    def index
      @previous_demarches_still_active = current_user
        .dossiers
        .includes(:procedure)
        .map(&:procedure)
        .uniq
        .filter(&:publiee?)

      @popular_demarches = Procedure
        .includes(:service)
        .select("procedures.*, COUNT(*) AS procedures_count")
        .joins(:dossiers)
        .publiees
        .where(dossiers: { created_at: 7.days.ago..Time.zone.now })
        .group("procedures.id")
        .order("procedures_count DESC")
        .limit(5)
    end
  end
end

app/controllers/users/feedbacks_controller.rb
module Users
  class FeedbacksController < UserController
    def create
      current_user.feedbacks.create!(rating: params[:rating])
      flash.notice = "Merci de votre retour, si vous souhaitez nous en dire plus, n'hésitez pas à #{helpers.contact_link('nous contacter', type: Helpscout::FormAdapter::TYPE_AMELIORATION)}."
    end
  end
end

app/views/manager/users/emails.html.erb
<% content_for(:title) { "Emails vers #{@user.email}" } %>

<style>
  .hidden { display: none }
  .email-sent { color: green !important}
  .email-blocked { color: red }
</style>
<script type="text/javascript" charset="utf-8">
  function reveal_email(id) {
      document.querySelector(id).classList.toggle('hidden');
  }
</script>
<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>
</header>

<section class="main-content__body">
  <h2>Historique des email</h2>
<% if @transactionnal_emails.present? %>
  <p>
  Cet historique contient les 30 derniers jours. Pour un recherche plus fine, il faut <a href="https://app-smtp.sendinblue.com/log">fouiller les logs</a>.
  </p>
  <table>
    <thead>
    <tr>
      <th class="cell-label cell-label--string cell-label--false" scope="col" role="columnheader" aria-sort="none">
        Émetteur
      </th>
      <th class="cell-label cell-label--string cell-label--false" scope="col" role="columnheader" aria-sort="none">
        Sujet
      </th>
      <th class="cell-label cell-label--string cell-label--false" scope="col" role="columnheader" aria-sort="none">
        Date
      </th>
    </tr>
    </thead>
    <tbody>
      <% @transactionnal_emails&.transactional_emails&.reverse&.each do |email| %>
        <% matching_events = @events&.events&.select { |e| e.message_id == email.message_id } %>
      <tr class="<%= event_color_code(matching_events) %>">
        <td class="cell-data cell-data--string" style="">
          <%= email.from %>
        </td>
        <td class="cell-data cell-data--string" style="">
        <%= email.subject %>
        </td>
        <td class="cell-data cell-data--string" style="text-align: center;">
        <%= l(email.date.is_a?(String) ? Time.zone.parse(email.date) : email.date, format: '%d/%m/%y à %H:%M') %>
        </td>
        <td class="cell-data cell-data--string" style="text-align: center;">
          <ul>

          <% matching_events.each do |event|%>
          <li><%= event.event %></li>
          <% end %>
          </ul>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Historique indisponible. Cet email n'existe pas chez Sendinblue, ou nous n'avons pas réussi à échanger.
    Vous pouvez éventuellement <a href="https://app-smtp.sendinblue.com/log">fouiller leurs logs</a>.</p>
<% end %>

  <h2>Problèmes potentiel</h2>

  <% if @user.confirmed? %>
    <p><strong>Compte activé, n'arrive pas à se connecter</strong> ? <button class="btn btn-secondary btn-small" onclick="reveal_email('#activated-cant-connect')">Voir la suggestion d’email</button></p>
    <pre class="hidden" id="activated-cant-connect">
Bonjour,
votre compte est activé de notre côté.
Vous pouvez vous connecter à votre compte de deux manières :
- à cette adresse, afin de consulter vos dossiers : https://www.demarches-simplifiees.fr/users/sign_in
- depuis la page de démarrage d’une démarche qu'on vous a communiqué, afin de déposer un dossier.

Si vous avez oublié votre mot de passe, vous pouvez aussi en demander un nouveau via:
https://www.demarches-simplifiees.fr/users/password/new

Bien cordialement</pre>
  <% else %>
    <p><strong>Ce compte n'est pas activé</strong>. Vous pouvez lui <%= link_to('renvoyer l’email de confirmation', [:resend_confirmation_instructions, namespace, 'user'], method: :post, class: 'button') %>, puis un email. <button class="btn btn-secondary btn-small" onclick="reveal_email('#not-activated')">Voir la suggestion d’email</button> </p>
    <pre class="hidden" id="not-activated">
Bonjour,

Votre compte n'a pas été confirmé. Je vous ai transmis à nouveau un code de confirmation
dans un email séparé ; après avoir cliqué sur le lien qui s'y trouve, vous pourrez vous connecter
à votre compte, voir les dossiers déposés et en déposer de nouveaux.

Si vous avez oublié votre mot de passe, vous pouvez aussi en demander un autre via:
https://www.demarches-simplifiees.fr/users/password/new

Cordialement</pre>
  <% end %>
  <p><strong>Compte <a href="https://app-smtp.sendinblue.com/block">bloqué</a> chez Sendinblue ?</strong> Vous pouvez le <%= link_to('débloquer', manager_user_unblock_email_path(@user), method: :put, class: 'button', remote: true) %>  puis lui envoyer <button class="btn btn-secondary btn-small" onclick="reveal_email('#unblock_email')">le mail suivant</button></p>
    <pre class="hidden" id="unblock_email">
Bonjour,

votre email était bloqué par notre prestataire.
Je l'ai débloqué, vous devriez recevoir les mails à venir.

Cela peut arriver si vous, ou ceux qui gèrent vos emails, marquent nos emails comme spam.

Nous vous invitons donc à autoriser les emails émis depuis demarches-simplifiees.fr

Bien cordialement</pre>
<p><strong>Problème chez Sendinblue ?</strong> Regardez leur <a href="https://status.sendinblue.com/">page de status</a>. <button class="btn btn-secondary btn-small" onclick="reveal_email('#pb-sendinblue')">Voir la suggestion d’email</button></p>
  <pre class="hidden" id="pb-sendinblue">
Bonjour,
Désolé, notre prestataire d'envoi d'email subit actuellement des soucis avec sa plateforme ;
vous allez recevoir cet email sous peu.

Bien cordialement,</pre>
</section>

app/views/manager/users/show.html.erb
<%#
# Show

This view is the template for the show page.
It renders the attributes of a resource,
as well as a link to its edit page.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Show][1].
  Contains methods for accessing the resource to be displayed on the page,
  as well as helpers for describing how each attribute of the resource
  should be displayed.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Show
%>

<% content_for(:title) { t("administrate.actions.show_resource", name: page.page_title) } %>
<% user = page.resource %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= button_to "modifier", edit_manager_user_path(page.resource), method: :get, class: "button" %>
  </div>
  <div>
    <%= button_to "supprimer", delete_manager_user_path(page.resource), method: :delete, disabled: !page.resource.can_be_deleted?, class: "button", data: { confirm: "Confirmez-vous la suppression de l'utilisateur ?" }, title: page.resource.can_be_deleted? ? "Supprimer" : "Cet utilisateur ne peut être supprimé. Il a des dossiers dont l'instruction a commencé ou il est administrateur ou instructeur" %>
  </div>
  <div>
    <% if !user.confirmed? %>
      <%= link_to('Renvoyer l’email de confirmation', [:resend_confirmation_instructions, namespace, page.resource], method: :post, class: 'button') %>
    <% end %>
  </div>
</header>

<section class="main-content__body">
  <%= render partial: 'manager/application/user_meta', locals: {user: user} %>
  <dl>
    <% page.attributes.each do |attribute| %>
      <dt class="attribute-label" id="<%= attribute.name %>">
      <%= t(
        "helpers.label.#{resource_name}.#{attribute.name}",
        default: attribute.name.titleize,
      ) %>
      </dt>

      <dd class="attribute-data attribute-data--<%=attribute.html_class%>"
          ><%= render_field attribute, page: page %></dd>
    <% end %>
  </dl>
</section>