config/routes.rb
Rails.application.routes.draw do
  get '/saml/auth' => 'saml_idp#new'
  post '/saml/auth' => 'saml_idp#create'
  get '/saml/metadata' => 'saml_idp#metadata'

  #
  # Manager
  #

  namespace :manager do
    resources :procedures, only: [:index, :show] do
      post 'whitelist', on: :member
      post 'draft', on: :member
      post 'discard', on: :member
      post 'restore', on: :member
      post 'add_administrateur', on: :member
      post 'change_piece_justificative_template', on: :member
      get 'export_mail_brouillons', on: :member
    end

    resources :dossiers, only: [:index, :show] do
      post 'discard', on: :member
      post 'restore', on: :member
      post 'repasser_en_instruction', on: :member
    end

    resources :administrateurs, only: [:index, :show, :new, :create] do
      post 'reinvite', on: :member
      delete 'delete', on: :member
    end

    resources :users, only: [:index, :show, :edit, :update] do
      delete 'delete', on: :member
      post 'resend_confirmation_instructions', on: :member
      put 'enable_feature', on: :member
      get 'emails', on: :member
      put 'unblock_email'
    end

    resources :instructeurs, only: [:index, :show] do
      post 'reinvite', on: :member
      delete 'delete', on: :member
    end

    resources :dossiers, only: [:show]

    resources :demandes, only: [:index]

    resources :bill_signatures, only: [:index]

    resources :services, only: [:index, :show]

    post 'demandes/create_administrateur'
    post 'demandes/refuse_administrateur'

    authenticate :super_admin do
      mount Flipper::UI.app(-> { Flipper.instance }) => "/features", as: :flipper
      match "/delayed_job" => DelayedJobWeb, :anchor => false, :via => [:get, :post]
    end

    root to: "administrateurs#index"
  end

  #
  # Letter Opener
  #

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  #
  # Monitoring
  #

  get "/ping" => "ping#index"

  #
  # Authentication
  #

  devise_for :super_admins, skip: [:registrations], controllers: {
    sessions: 'super_admins/sessions',
    passwords: 'super_admins/passwords'
  }

  devise_scope :super_admin do
    get '/super_admins/password/test_strength' => 'super_admins/passwords#test_strength'
  end

  get 'super_admins/edit_otp', to: 'super_admins#edit_otp', as: 'edit_super_admin_otp'
  put 'super_admins/enable_otp', to: 'super_admins#enable_otp', as: 'enable_super_admin_otp'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    get '/users/no_procedure' => 'users/sessions#no_procedure'
    get 'connexion-par-jeton/:id' => 'users/sessions#sign_in_by_link', as: 'sign_in_by_link'
    get 'lien-envoye/:email' => 'users/sessions#link_sent', constraints: { email: /.*/ }, as: 'link_sent'
  end

  devise_scope :administrateur do
    get '/administrateurs/password/test_strength' => 'administrateurs/passwords#test_strength'
  end

  #
  # Main routes
  #

  root 'root#index'
  get '/administration' => 'root#administration'

  get 'users' => 'users#index'
  get 'admin' => 'admin#index'

  get '/stats' => 'stats#index'
  get '/stats/download' => 'stats#download'

  namespace :france_connect do
    get 'particulier' => 'particulier#login'
    get 'particulier/callback' => 'particulier#callback'
  end

  namespace :champs do
    get ':position/siret', to: 'siret#show', as: :siret
    get ':position/dossier_link', to: 'dossier_link#show', as: :dossier_link
    post ':position/carte', to: 'carte#show', as: :carte

    get ':champ_id/carte/features', to: 'carte#index', as: :carte_features
    post ':champ_id/carte/features', to: 'carte#create'
    post ':champ_id/carte/features/import', to: 'carte#import'
    patch ':champ_id/carte/features/:id', to: 'carte#update'
    delete ':champ_id/carte/features/:id', to: 'carte#destroy'

    post ':position/repetition', to: 'repetition#show', as: :repetition
    put 'piece_justificative/:champ_id', to: 'piece_justificative#update', as: :piece_justificative
  end

  resources :attachments, only: [:show, :destroy]

  get "patron" => "root#patron"
  get "accessibilite" => "root#accessibilite"
  get "suivi" => "root#suivi"
  post "dismiss_outdated_browser" => "root#dismiss_outdated_browser"

  get "contact", to: "support#index"
  post "contact", to: "support#create"

  get "contact-admin", to: "support#admin"

  post "webhooks/helpscout", to: "webhook#helpscout"
  match "webhooks/helpscout", to: lambda { |_| [204, {}, nil] }, via: :head

  #
  # Deprecated UI
  #

  namespace :users do
    resources :dossiers, only: [] do
      post '/carte/zones' => 'carte#zones'
      get '/carte' => 'carte#show'
      post '/carte' => 'carte#save'
      post '/repousser-expiration' => 'dossiers#extend_conservation'
    end

    # Redirection of legacy "/users/dossiers" route to "/dossiers"
    get 'dossiers', to: redirect('/dossiers')
    get 'dossiers/:id/recapitulatif', to: redirect('/dossiers/%{id}')
    get 'dossiers/invites/:id', to: redirect(path: '/invites/%{id}')

    get 'activate' => '/users/activate#new'
    patch 'activate' => '/users/activate#create'
  end

  # order matters: we don't want those routes to match /admin/procedures/:id
  get 'admin/procedures/new' => 'new_administrateur/procedures#new', as: :new_admin_procedure

  namespace :admin do
    get 'activate' => '/administrateurs/activate#new'
    patch 'activate' => '/administrateurs/activate#create'
    get 'procedures/archived', to: redirect('/admin/procedures?statut=archivees')
    get 'procedures/draft', to: redirect('/admin/procedures?statut=brouillons')

    resources :procedures, only: [:destroy] do
      collection do
        get 'new_from_existing' => 'procedures#new_from_existing', as: :new_from_existing
      end

      member do
        delete :delete_logo
        delete :delete_deliberation
        delete :delete_notice
      end

      put 'archive' => 'procedures#archive', as: :archive
      get 'publish_validate' => 'procedures#publish_validate', as: :publish_validate
      put 'clone' => 'procedures#clone', as: :clone
    end

    namespace :assigns do
      get 'show' # delete after fixed tests admin/instructeurs/show_spec without this line
    end

    resources :instructeurs, only: [:index, :create, :destroy]
  end

  resources :invites, only: [:show, :destroy] do
    collection do
      post 'dossier/:dossier_id', to: 'invites#create', as: :dossier
    end
  end

  #
  # API
  #

  authenticated :user, lambda { |user| user.administrateur_id } do
    mount GraphqlPlayground::Rails::Engine, at: "/graphql", graphql_path: "/api/v2/graphql"
  end

  namespace :api do
    namespace :v1 do
      resources :procedures, only: [:index, :show] do
        resources :dossiers, only: [:index, :show]
      end
    end

    namespace :v2 do
      post :graphql, to: "graphql#execute"
      get 'dossiers/pdf/:id', format: :pdf, to: "dossiers#pdf", as: :dossier_pdf
      get 'dossiers/geojson/:id', to: "dossiers#geojson", as: :dossier_geojson
    end
  end

  #
  # User
  #

  scope module: 'users' do
    namespace :commencer do
      get '/test/:path/dossier_vide', action: 'dossier_vide_pdf_test', as: :dossier_vide_test
      get '/test/:path', action: 'commencer_test', as: :test
      get '/:path', action: 'commencer'
      get '/:path/dossier_vide', action: 'dossier_vide_pdf', as: :dossier_vide
      get '/:path/sign_in', action: 'sign_in', as: :sign_in
      get '/:path/sign_up', action: 'sign_up', as: :sign_up
      get '/:path/france_connect', action: 'france_connect', as: :france_connect
    end

    resources :dossiers, only: [:index, :show, :new] do
      member do
        get 'identite'
        patch 'update_identite'
        get 'siret'
        post 'siret', to: 'dossiers#update_siret'
        get 'etablissement'
        get 'brouillon'
        patch 'brouillon', to: 'dossiers#update_brouillon'
        get 'modifier', to: 'dossiers#modifier'
        patch 'modifier', to: 'dossiers#update'
        get 'merci'
        get 'demande'
        get 'messagerie'
        post 'commentaire' => 'dossiers#create_commentaire'
        post 'ask_deletion'
        get 'attestation'
      end

      collection do
        get 'recherche'
      end
    end
    resource :feedback, only: [:create]
    get 'demarches' => 'demarches#index'

    get 'profil' => 'profil#show'
    post 'renew-api-token' => 'profil#renew_api_token'
    # allow refresh 'renew api token' page
    get 'renew-api-token' => redirect('/profil')
    patch 'update_email' => 'profil#update_email'
  end

  #
  # Expert
  #
  scope module: 'experts', as: 'expert' do
    get 'avis', to: 'avis#index', as: 'all_avis'

    # this redirections are ephemeral, to ensure that emails sent to experts before are still valid
    # TODO : they will be removed in September, 2020
    get 'avis/:id', to: redirect('/procedures/old/avis/%{id}')
    get 'avis/:id/sign_up/email/:email', to: redirect("/procedures/old/avis/%{id}/sign_up/email/%{email}"), constraints: { email: /.*/ }

    resources :procedures, only: [], param: :procedure_id do
      member do
        resources :avis, only: [:show, :update] do
          get '', action: 'procedure', on: :collection, as: :procedure
          member do
            get 'instruction'
            get 'messagerie'
            post 'commentaire' => 'avis#create_commentaire'
            post 'avis' => 'avis#create_avis'
            get 'bilans_bdf'

            get 'sign_up/email/:email' => 'avis#sign_up', constraints: { email: /.*/ }, as: 'sign_up'
            post 'sign_up/email/:email' => 'avis#update_expert', constraints: { email: /.*/ }
          end
        end
      end
    end
  end

  #
  # Instructeur
  #

  scope module: 'instructeurs', as: 'instructeur' do
    get 'avis', to: 'avis#index', as: 'all_avis'

app/controllers/admin/procedures_controller.rb
class Admin::ProceduresController < AdminController
  include SmartListing::Helper::ControllerExtensions
  helper SmartListing::Helper

  before_action :retrieve_procedure, only: [:show, :delete_logo, :delete_deliberation, :delete_notice, :publish_validate, :publish]

  def index
    if current_administrateur.procedures.count != 0
      @procedures = smart_listing_create :procedures,
        current_administrateur.procedures.publiees.order(published_at: :desc),
        partial: "admin/procedures/list",
        array: true

      active_class
    else
      redirect_to new_from_existing_admin_procedures_path
    end
  end

  def show
    if @procedure.brouillon?
      @procedure_lien = commencer_test_url(path: @procedure.path)
    else
      @procedure_lien = commencer_url(path: @procedure.path)
    end
    @procedure.path = @procedure.suggested_path(current_administrateur)
    @current_administrateur = current_administrateur
  end

  def destroy
    procedure = current_administrateur.procedures.find(params[:id])

    if procedure.can_be_deleted_by_administrateur?
      procedure.discard_and_keep_track!(current_administrateur)

      flash.notice = 'Démarche supprimée'
      redirect_to admin_procedures_draft_path
    else
      render json: {}, status: 403
    end
  end

  def archive
    procedure = current_administrateur.procedures.find(params[:procedure_id])
    procedure.close!

    flash.notice = "Démarche close"
    redirect_to admin_procedures_path

  rescue ActiveRecord::RecordNotFound
    flash.alert = 'Démarche inexistante'
    redirect_to admin_procedures_path
  end

  def clone
    procedure = Procedure.find(params[:procedure_id])
    new_procedure = procedure.clone(current_administrateur, cloned_from_library?)

    if new_procedure.valid?
      flash.notice = 'Démarche clonée'
      redirect_to edit_admin_procedure_path(id: new_procedure.id)
    else
      if cloned_from_library?
        flash.alert = new_procedure.errors.full_messages
        redirect_to new_from_existing_admin_procedures_path
      else
        flash.alert = new_procedure.errors.full_messages
        redirect_to admin_procedures_path
      end
    end

  rescue ActiveRecord::RecordNotFound
    flash.alert = 'Démarche inexistante'
    redirect_to admin_procedures_path
  end

  SIGNIFICANT_DOSSIERS_THRESHOLD = 30

  def new_from_existing
    significant_procedure_ids = Procedure
      .publiees_ou_closes
      .joins(:dossiers)
      .group("procedures.id")
      .having("count(dossiers.id) >= ?", SIGNIFICANT_DOSSIERS_THRESHOLD)
      .pluck('procedures.id')

    @grouped_procedures = Procedure
      .includes(:administrateurs, :service)
      .where(id: significant_procedure_ids)
      .group_by(&:organisation_name)
      .sort_by { |_, procedures| procedures.first.created_at }
    render layout: 'application'
  end

  def active_class
    @active_class = 'active'
  end

  def archived_class
    @archived_class = 'active'
  end

  def draft_class
    @draft_class = 'active'
  end

  def delete_logo
    @procedure.logo.purge_later

    flash.notice = 'le logo a bien été supprimé'
    redirect_to edit_admin_procedure_path(@procedure)
  end

  def delete_deliberation
    @procedure.deliberation.purge_later

    flash.notice = 'la délibération a bien été supprimée'
    redirect_to edit_admin_procedure_path(@procedure)
  end

  def delete_notice
    @procedure.notice.purge_later

    flash.notice = 'la notice a bien été supprimée'
    redirect_to edit_admin_procedure_path(@procedure)
  end

  private

  def cloned_from_library?
    params[:from_new_from_existing].present?
  end

  def publish_params
    params.permit(:path, :lien_site_web)
  end

  def procedure_params
    editable_params = [:libelle, :description, :organisation, :direction, :lien_site_web, :cadre_juridique, :deliberation, :notice, :web_hook_url, :euro_flag, :logo, :auto_archive_on]
    permited_params = if @procedure&.locked?
      params.require(:procedure).permit(*editable_params)
    else
      params.require(:procedure).permit(*editable_params, :duree_conservation_dossiers_dans_ds, :duree_conservation_dossiers_hors_ds, :for_individual, :path)
    end
    permited_params
  end
end

app/controllers/api/v1/procedures_controller.rb
class API::V1::ProceduresController < APIController
  before_action :fetch_procedure_and_check_token

  def show
    render json: { procedure: ProcedureSerializer.new(@procedure).as_json }
  end

  private

  def fetch_procedure_and_check_token
    @procedure = Procedure.for_api.find(params[:id])

    administrateur = find_administrateur_for_token(@procedure)
    if administrateur
      Current.administrateur = administrateur
    else
      render json: {}, status: :unauthorized
    end

  rescue ActiveRecord::RecordNotFound
    render json: {}, status: :not_found
  end
end

app/controllers/new_administrateur/administrateur_controller.rb
module NewAdministrateur
  class AdministrateurController < ApplicationController
    before_action :authenticate_administrateur!

    def retrieve_procedure
      id = params[:procedure_id] || params[:id]

      @procedure = current_administrateur.procedures.find(id)

    rescue ActiveRecord::RecordNotFound
      flash.alert = 'Démarche inexistante'
      redirect_to admin_procedures_path, status: 404
    end

    def procedure_locked?
      if @procedure.locked?
        flash.alert = 'Démarche verrouillée'
        redirect_to admin_procedure_path(@procedure)
      end
    end

    def reset_procedure
      if @procedure.brouillon?
        @procedure.reset!
      end
    end
  end
end

app/helpers/procedure_helper.rb
module ProcedureHelper
  def procedure_lien(procedure)
    if procedure.brouillon?
      commencer_test_url(path: procedure.path)
    else
      commencer_url(path: procedure.path)
    end
  end

  def procedure_libelle(procedure)
    parts = procedure.brouillon? ? [tag.span('démarche en test', class: 'badge')] : []
    parts << procedure.libelle
    safe_join(parts, ' ')
  end

  def procedure_publish_text(procedure, key)
    # i18n-tasks-use t('modal.publish.body.publish')
    # i18n-tasks-use t('modal.publish.body.reopen')
    # i18n-tasks-use t('modal.publish.submit.publish')
    # i18n-tasks-use t('modal.publish.submit.reopen')
    # i18n-tasks-use t('modal.publish.title.publish')
    # i18n-tasks-use t('modal.publish.title.reopen')
    action = procedure.close? ? :reopen : :publish
    t(action, scope: [:modal, :publish, key])
  end

  def types_de_champ_data(procedure)
    {
      isAnnotation: false,
      typeDeChampsTypes: TypeDeChamp.type_de_champ_types_for(procedure, current_user),
      typeDeChamps: (procedure.draft_revision ? procedure.draft_revision : procedure).types_de_champ.as_json_for_editor,
      baseUrl: admin_procedure_types_de_champ_path(procedure),
      directUploadUrl: rails_direct_uploads_url
    }
  end

  def types_de_champ_private_data(procedure)
    {
      isAnnotation: true,
      typeDeChampsTypes: TypeDeChamp.type_de_champ_types_for(procedure, current_user),
      typeDeChamps: (procedure.draft_revision ? procedure.draft_revision : procedure).types_de_champ_private.as_json_for_editor,
      baseUrl: admin_procedure_types_de_champ_path(procedure),
      directUploadUrl: rails_direct_uploads_url
    }
  end

  def procedure_auto_archive_date(procedure)
    I18n.l(procedure.auto_archive_on - 1.day, format: '%-d %B %Y')
  end

  def procedure_auto_archive_time(procedure)
    "à 23 h 59 (heure de " + Rails.application.config.time_zone + ")"
  end

  def procedure_auto_archive_datetime(procedure)
    procedure_auto_archive_date(procedure) + ' ' + procedure_auto_archive_time(procedure)
  end
end

app/views/new_administrateur/procedures/_procedure_transfert.html.haml
= form_tag admin_procedure_transfer_path(procedure_id: @procedure.id), method: :post, class: 'form' do
  .card
    %h2.card-title
      Envoyer une copie de cette démarche à un autre administrateur
    %p.mb-4
      Cette fonctionnalité vous permet de d'envoyer une copie de votre démarche à un autre administrateur.

    %div
      = text_field_tag :email_admin, '', { class: 'form-control',
            type: 'email',
            placeholder: 'Email administrateur cible' }

      = submit_tag "Envoyer à l'administrateur", class: 'button primary'

app/views/new_administrateur/procedures/annotations.html.haml
= render partial: 'new_administrateur/breadcrumbs',
  locals: { steps: [link_to('Démarches', admin_procedures_path),
                    link_to(@procedure.libelle, admin_procedure_path(@procedure)),
                    'Configuration des annotations privées'], preview: true }

.container
  %h1 Configuration des annotations privées
  %br

  = react_component("TypesDeChampEditor", types_de_champ_private_data(@procedure))

app/views/new_administrateur/procedures/apercu.html.haml
.dossiers-headers.sub-header
  .container
    %h1.page-title Prévisualisation de la démarche «&nbsp;#{@dossier.procedure.libelle}&nbsp;»

    %ul.tabs
      = tab_item('le dossier',
        apercu_admin_procedure_path(@dossier.procedure, tab: 'dossier'),
        active: @tab == 'dossier')
      - if @dossier.champs_private.size > 0
        = tab_item('les annotations privées',
          apercu_admin_procedure_path(@dossier.procedure, tab: 'annotations-privees'),
          active: @tab == 'annotations-privees')

- if @tab == 'dossier'
  = render partial: "shared/dossiers/edit", locals: { dossier: @dossier, apercu: true }
- else
  .container
    = form_for @dossier, url: '', method: :get, html: { class: 'form' } do |f|
      = f.fields_for :champs_private, @dossier.champs_private do |champ_form|
        - champ = champ_form.object
        = render partial: "shared/dossiers/editable_champs/editable_champ",
          locals: { champ: champ, form: champ_form }

app/views/new_administrateur/procedures/show.html.haml
= render partial: 'new_administrateur/breadcrumbs',
  locals: { steps: [link_to('Démarches', admin_procedures_path),
                    "#{@procedure.libelle} (crée le #{@procedure.created_at.strftime('%d/%m/%Y')})", "#{@procedure.close? ? "Close" : @procedure.locked? ? "Publiée" : "Brouillon"}"] }

.container.procedure-admin-container
  = link_to apercu_admin_procedure_path(@procedure), class: 'button', id: "preview-procedure" do
    %span.icon.preview
    Prévisualiser

  - if @procedure.brouillon?
    = link_to sanitize_url(@procedure_lien), target: :blank, rel: :noopener, class: 'button' do
      %span.icon.in-progress
      Tester

  - if @procedure.publiee? || @procedure.brouillon?
    = link_to admin_procedure_transfert_path(@procedure), class: 'button' do
      %span.icon.reply
      Envoyer une copie

  - if !@procedure.publiee? && !@procedure.close? && !@procedure.depubliee?
    = link_to 'Publier', admin_procedure_publication_path(@procedure), class: 'button primary', id: 'publish-procedure-link', data: { disable_with: "Publication..." }

  - if @procedure.close? || @procedure.depubliee?
    = link_to 'Réactiver', admin_procedure_publication_path(@procedure), class: 'button primary', id: 'publish-procedure-link', data: { disable_with: "Publication..." }

  - if @procedure.locked? && !@procedure.close?
    = link_to admin_procedure_archive_path(procedure_id: @procedure.id), method: :put, class: 'button', id: "close-procedure-link", data: { confirm:  "Voulez-vous vraiment clore la démarche ? \nLes dossiers en cours pourront être instruits, mais aucun nouveau dossier ne pourra plus être déposé.", disable_with: "Archivage..."} do
      %span.icon.archive
      Clore

.container
  %h2.procedure-admin-explanation Indispensable avant publication
  .procedure-grid
    .card-admin
      %div
        %span.icon.accept
        %p.card-admin-status-accept Validé
      %div
        %p.card-admin-title Présentation
        %p.card-admin-subtitle Logo, nom, description
      .card-admin-action
        = link_to 'Modifier', edit_admin_procedure_path(@procedure), class: 'button', id: "presentation"

    - if !@procedure.locked?
      .card-admin
        - if @procedure.draft_types_de_champ.count > 0
          %div
            %span.icon.accept
            %p.card-admin-status-accept Validé
        - else
          %div
            %span.icon.clock
            %p.card-admin-status-todo À faire
        %div
          %p.card-admin-title
            %span.badge.baseline= @procedure.draft_types_de_champ.count
            Champs du formulaire
          %p.card-admin-subtitle À remplir par les usagers
        .card-admin-action
          = link_to 'Modifier', champs_admin_procedure_path(@procedure), class: 'button'

    .card-admin
      - if @procedure.service_id.present?
        %div
          %span.icon.accept
          %p.card-admin-status-accept Validé
      - else
        %div
          %span.icon.clock
          %p.card-admin-status-todo À faire
      %div
        %p.card-admin-title Service
        %p.card-admin-subtitle
          - if @procedure.service_id.present?
            = @procedure.service.nom
          - else
            Choix du service administratif
      .card-admin-action
        - if @procedure.service.present?
          = link_to 'Modifier', edit_admin_service_path(@procedure.service, procedure_id: @procedure.id), class: 'button'
        - elsif current_administrateur.services.present?
          = link_to 'Choisir', admin_services_path(procedure_id: @procedure.id), class: 'button'
        - else
          = link_to 'Remplir', new_admin_service_path(procedure_id: @procedure.id), class: 'button'

    .card-admin
      %div
        %span.icon.accept
        %p.card-admin-status-accept Validé
      %div
        %p.card-admin-title
          %span.badge.baseline= @procedure.administrateurs.count
          #{"Administrateur".pluralize(@procedure.administrateurs.count)}

        %p.card-admin-subtitle Gestion de la démarche
      .card-admin-action
        = link_to 'Modifier', admin_procedure_administrateurs_path(@procedure), class: 'button', id: "administrateurs"

    .card-admin
      - if feature_enabled?(:administrateur_routage)
        %div
          %span.icon.accept
          %p.card-admin-status-accept Validé
      - elsif @procedure.instructeurs.count > 1
        %div
          %span.icon.accept
          %p.card-admin-status-accept Validé
      - else
        %div
          %span.icon.clock
          %p.card-admin-status-todo À faire
      %div
        %p.card-admin-title
          - if feature_enabled?(:administrateur_routage)
            %span.badge.baseline= @procedure.groupe_instructeurs.count
          - else
            %span.badge.baseline= @procedure.instructeurs.count

          = feature_enabled?(:administrateur_routage) ? "Groupe Instructeurs" : "#{"Instructeur".pluralize(@procedure.instructeurs.count)}"
        %p.card-admin-subtitle Suivi des dossiers
      .card-admin-action
        - if feature_enabled?(:administrateur_routage)
          = link_to 'Modifier', admin_procedure_groupe_instructeurs_path(@procedure), class: 'button', id: "groupe-instructeurs"
        - else
          = link_to 'Modifier', admin_procedure_groupe_instructeur_path(@procedure, @procedure.defaut_groupe_instructeur), class: 'button', id: "instructeurs"

  %h2.procedure-admin-explanation Pour aller plus loin
  .procedure-grid
    .card-admin
      - if @procedure.attestation_template.present? && @procedure.attestation_template.activated
        %div
          %span.icon.accept
          %p.card-admin-status-accept Activée
      - else
        %div
          %span.icon.clock
          %p.card-admin-status-todo Désactivée
      %div
        %p.card-admin-title Attestation
        %p.card-admin-subtitle Délivrance automatique pour les dossiers acceptés
      .card-admin-action
        = link_to 'Modifier', edit_admin_procedure_attestation_template_path(@procedure), class: 'button'

    .card-admin
      - if @procedure.allow_expert_review?
        %div
          %span.icon.accept
          %p.card-admin-status-accept Activé
      - else
        %div
          %span.icon.clock
          %p.card-admin-status-todo Désactivée
      %div
        %p.card-admin-title Avis externes
        %p.card-admin-subtitle Demander des avis aux experts invités
      .card-admin-action
        = link_to "#{@procedure.allow_expert_review? ? 'Désactiver' : 'Activer'}", allow_expert_review_admin_procedure_path(@procedure), method: :put,  class: 'button'

    - if @procedure.allow_expert_review?
      .card-admin
        %div
          %span.icon.preview
          %p.card-admin-status-todo À voir

        %div
          %p.card-admin-title Liste des experts
          %p.card-admin-subtitle Liste des experts invités par les instructeurs

        .card-admin-action
          = link_to "Voir", admin_procedure_invited_expert_list_path(@procedure), class: 'button'


    .card-admin
      %div
        %span.icon.clock
        %p.card-admin-status-todo À configurer
      %div
        %p.card-admin-title Configuration des emails
        %p.card-admin-subtitle Notifications automatiques
      .card-admin-action
        = link_to 'Modifier', admin_procedure_mail_templates_path(@procedure), class: 'button'

    - if !@procedure.locked?
      .card-admin
        - if @procedure.draft_types_de_champ_private.present?
          %div
            %span.icon.accept
            %p.card-admin-status-accept Validé
        - else
          %div
            %span.icon.clock
            %p.card-admin-status-todo À configurer
        %div
          %p.card-admin-title Annotations privées
          %p.card-admin-subtitle Champs à remplir par l’administration
        .card-admin-action
          = link_to 'Modifier', annotations_admin_procedure_path(@procedure), class: 'button'

    .card-admin
      - if @procedure.api_entreprise_token.present?
        %div
          %span.icon.accept
          %p.card-admin-status-accept Validé
      - else
        %div
          %span.icon.clock
          %p.card-admin-status-todo À configurer
      %div
        %p.card-admin-title Jeton
        %p.card-admin-subtitle Configurer le jeton API entreprise
      .card-admin-action
        = link_to 'Modifier', jeton_admin_procedure_path(@procedure), class: 'button'

    .card-admin
      - if @procedure.monavis_embed.present?
        %div
          %span.icon.accept
          %p.card-admin-status-accept Validé
      - else
        %div
          %span.icon.clock
          %p.card-admin-status-todo À configurer
      %div
        %p.card-admin-title MonAvis
        %p.card-admin-subtitle Avis des usagers sur votre démarche
      .card-admin-action
        = link_to 'Modifier', monavis_admin_procedure_path(@procedure), class: 'button'