config/routes.rb
Rails.application.routes.draw do
  get '/saml/auth' => 'saml_idp#new'
  post '/saml/auth' => 'saml_idp#create'
  get '/saml/metadata' => 'saml_idp#metadata'

  #
  # Manager
  #

  namespace :manager do
    resources :procedures, only: [:index, :show] do
      post 'whitelist', on: :member
      post 'draft', on: :member
      post 'discard', on: :member
      post 'restore', on: :member
      post 'add_administrateur', on: :member
      post 'change_piece_justificative_template', on: :member
      get 'export_mail_brouillons', on: :member
    end

    resources :dossiers, only: [:index, :show] do
      post 'discard', on: :member
      post 'restore', on: :member
      post 'repasser_en_instruction', on: :member
    end

    resources :administrateurs, only: [:index, :show, :new, :create] do
      post 'reinvite', on: :member
      delete 'delete', on: :member
    end

    resources :users, only: [:index, :show, :edit, :update] do
      delete 'delete', on: :member
      post 'resend_confirmation_instructions', on: :member
      put 'enable_feature', on: :member
      get 'emails', on: :member
      put 'unblock_email'
    end

    resources :instructeurs, only: [:index, :show] do
      post 'reinvite', on: :member
      delete 'delete', on: :member
    end

    resources :dossiers, only: [:show]

    resources :demandes, only: [:index]

    resources :bill_signatures, only: [:index]

    resources :services, only: [:index, :show]

    post 'demandes/create_administrateur'
    post 'demandes/refuse_administrateur'

    authenticate :super_admin do
      mount Flipper::UI.app(-> { Flipper.instance }) => "/features", as: :flipper
      match "/delayed_job" => DelayedJobWeb, :anchor => false, :via => [:get, :post]
    end

    root to: "administrateurs#index"
  end

  #
  # Letter Opener
  #

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  #
  # Monitoring
  #

  get "/ping" => "ping#index"

  #
  # Authentication
  #

  devise_for :super_admins, skip: [:registrations], controllers: {
    sessions: 'super_admins/sessions',
    passwords: 'super_admins/passwords'
  }

  devise_scope :super_admin do
    get '/super_admins/password/test_strength' => 'super_admins/passwords#test_strength'
  end

  get 'super_admins/edit_otp', to: 'super_admins#edit_otp', as: 'edit_super_admin_otp'
  put 'super_admins/enable_otp', to: 'super_admins#enable_otp', as: 'enable_super_admin_otp'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    get '/users/no_procedure' => 'users/sessions#no_procedure'
    get 'connexion-par-jeton/:id' => 'users/sessions#sign_in_by_link', as: 'sign_in_by_link'
    get 'lien-envoye/:email' => 'users/sessions#link_sent', constraints: { email: /.*/ }, as: 'link_sent'
  end

  devise_scope :administrateur do
    get '/administrateurs/password/test_strength' => 'administrateurs/passwords#test_strength'
  end

  #
  # Main routes
  #

  root 'root#index'
  get '/administration' => 'root#administration'

  get 'users' => 'users#index'
  get 'admin' => 'admin#index'

  get '/stats' => 'stats#index'
  get '/stats/download' => 'stats#download'

  namespace :france_connect do
    get 'particulier' => 'particulier#login'
    get 'particulier/callback' => 'particulier#callback'
  end

  namespace :champs do
    get ':position/siret', to: 'siret#show', as: :siret
    get ':position/dossier_link', to: 'dossier_link#show', as: :dossier_link
    post ':position/carte', to: 'carte#show', as: :carte

    get ':champ_id/carte/features', to: 'carte#index', as: :carte_features
    post ':champ_id/carte/features', to: 'carte#create'
    post ':champ_id/carte/features/import', to: 'carte#import'
    patch ':champ_id/carte/features/:id', to: 'carte#update'
    delete ':champ_id/carte/features/:id', to: 'carte#destroy'

    post ':position/repetition', to: 'repetition#show', as: :repetition
    put 'piece_justificative/:champ_id', to: 'piece_justificative#update', as: :piece_justificative
  end

  resources :attachments, only: [:show, :destroy]

  get "patron" => "root#patron"
  get "accessibilite" => "root#accessibilite"
  get "suivi" => "root#suivi"
  post "dismiss_outdated_browser" => "root#dismiss_outdated_browser"

  get "contact", to: "support#index"
  post "contact", to: "support#create"

  get "contact-admin", to: "support#admin"

  post "webhooks/helpscout", to: "webhook#helpscout"
  match "webhooks/helpscout", to: lambda { |_| [204, {}, nil] }, via: :head

  #
  # Deprecated UI
  #

  namespace :users do
    resources :dossiers, only: [] do
      post '/carte/zones' => 'carte#zones'
      get '/carte' => 'carte#show'
      post '/carte' => 'carte#save'
      post '/repousser-expiration' => 'dossiers#extend_conservation'
    end

    # Redirection of legacy "/users/dossiers" route to "/dossiers"
    get 'dossiers', to: redirect('/dossiers')
    get 'dossiers/:id/recapitulatif', to: redirect('/dossiers/%{id}')
    get 'dossiers/invites/:id', to: redirect(path: '/invites/%{id}')

    get 'activate' => '/users/activate#new'
    patch 'activate' => '/users/activate#create'
  end

  # order matters: we don't want those routes to match /admin/procedures/:id
  get 'admin/procedures/new' => 'new_administrateur/procedures#new', as: :new_admin_procedure

  namespace :admin do
    get 'activate' => '/administrateurs/activate#new'
    patch 'activate' => '/administrateurs/activate#create'
    get 'procedures/archived', to: redirect('/admin/procedures?statut=archivees')
    get 'procedures/draft', to: redirect('/admin/procedures?statut=brouillons')

    resources :procedures, only: [:destroy] do
      collection do
        get 'new_from_existing' => 'procedures#new_from_existing', as: :new_from_existing
      end

      member do
        delete :delete_logo
        delete :delete_deliberation
        delete :delete_notice
      end

      put 'archive' => 'procedures#archive', as: :archive
      get 'publish_validate' => 'procedures#publish_validate', as: :publish_validate
      put 'clone' => 'procedures#clone', as: :clone
    end

    namespace :assigns do
      get 'show' # delete after fixed tests admin/instructeurs/show_spec without this line
    end

    resources :instructeurs, only: [:index, :create, :destroy]
  end

  resources :invites, only: [:show, :destroy] do
    collection do
      post 'dossier/:dossier_id', to: 'invites#create', as: :dossier
    end
  end

  #
  # API
  #

  authenticated :user, lambda { |user| user.administrateur_id } do
    mount GraphqlPlayground::Rails::Engine, at: "/graphql", graphql_path: "/api/v2/graphql"
  end

  namespace :api do
    namespace :v1 do
      resources :procedures, only: [:index, :show] do
        resources :dossiers, only: [:index, :show]
      end
    end

    namespace :v2 do
      post :graphql, to: "graphql#execute"
      get 'dossiers/pdf/:id', format: :pdf, to: "dossiers#pdf", as: :dossier_pdf
      get 'dossiers/geojson/:id', to: "dossiers#geojson", as: :dossier_geojson
    end
  end

  #
  # User
  #

  scope module: 'users' do
    namespace :commencer do
      get '/test/:path/dossier_vide', action: 'dossier_vide_pdf_test', as: :dossier_vide_test
      get '/test/:path', action: 'commencer_test', as: :test
      get '/:path', action: 'commencer'
      get '/:path/dossier_vide', action: 'dossier_vide_pdf', as: :dossier_vide
      get '/:path/sign_in', action: 'sign_in', as: :sign_in
      get '/:path/sign_up', action: 'sign_up', as: :sign_up
      get '/:path/france_connect', action: 'france_connect', as: :france_connect
    end

    resources :dossiers, only: [:index, :show, :new] do
      member do
        get 'identite'
        patch 'update_identite'
        get 'siret'
        post 'siret', to: 'dossiers#update_siret'
        get 'etablissement'
        get 'brouillon'
        patch 'brouillon', to: 'dossiers#update_brouillon'
        get 'modifier', to: 'dossiers#modifier'
        patch 'modifier', to: 'dossiers#update'
        get 'merci'
        get 'demande'
        get 'messagerie'
        post 'commentaire' => 'dossiers#create_commentaire'
        post 'ask_deletion'
        get 'attestation'
      end

      collection do
        get 'recherche'
      end
    end
    resource :feedback, only: [:create]
    get 'demarches' => 'demarches#index'

    get 'profil' => 'profil#show'
    post 'renew-api-token' => 'profil#renew_api_token'
    # allow refresh 'renew api token' page
    get 'renew-api-token' => redirect('/profil')
    patch 'update_email' => 'profil#update_email'
  end

  #
  # Expert
  #
  scope module: 'experts', as: 'expert' do
    get 'avis', to: 'avis#index', as: 'all_avis'

    # this redirections are ephemeral, to ensure that emails sent to experts before are still valid
    # TODO : they will be removed in September, 2020
    get 'avis/:id', to: redirect('/procedures/old/avis/%{id}')
    get 'avis/:id/sign_up/email/:email', to: redirect("/procedures/old/avis/%{id}/sign_up/email/%{email}"), constraints: { email: /.*/ }

    resources :procedures, only: [], param: :procedure_id do
      member do
        resources :avis, only: [:show, :update] do
          get '', action: 'procedure', on: :collection, as: :procedure
          member do
            get 'instruction'
            get 'messagerie'
            post 'commentaire' => 'avis#create_commentaire'
            post 'avis' => 'avis#create_avis'
            get 'bilans_bdf'

            get 'sign_up/email/:email' => 'avis#sign_up', constraints: { email: /.*/ }, as: 'sign_up'
            post 'sign_up/email/:email' => 'avis#update_expert', constraints: { email: /.*/ }
          end
        end
      end
    end
  end

  #
  # Instructeur
  #

  scope module: 'instructeurs', as: 'instructeur' do
    get 'avis', to: 'avis#index', as: 'all_avis'

app/controllers/api/v1/dossiers_controller.rb
class API::V1::DossiersController < APIController
  before_action :fetch_procedure_and_check_token

  DEFAULT_PAGE_SIZE = 100
  MAX_PAGE_SIZE = 1000
  ORDER_DIRECTIONS = { 'asc' => :asc, 'desc' => :desc }

  def index
    dossiers = @dossiers.page(params[:page]).per(per_page)

    render json: { dossiers: dossiers.map { |dossier| DossiersSerializer.new(dossier) }, pagination: pagination(dossiers) }, status: 200
  rescue ActiveRecord::RecordNotFound
    render json: {}, status: 404
  end

  def show
    dossier = @dossiers.for_api.find(params[:id])

    respond_to do |format|
      format.json { render json: { dossier: DossierSerializer.new(dossier).as_json }, status: 200 }
    end
  rescue ActiveRecord::RecordNotFound
    render json: {}, status: 404
  end

  private

  def pagination(dossiers)
    {
      page: dossiers.current_page,
      resultats_par_page: dossiers.limit_value,
      nombre_de_page: dossiers.total_pages
    }
  end

  def per_page # inherited value from will_paginate
    resultats_par_page = params[:resultats_par_page]&.to_i
    if resultats_par_page && resultats_par_page > 0
      [resultats_par_page, MAX_PAGE_SIZE].min
    else
      DEFAULT_PAGE_SIZE
    end
  end

  def fetch_procedure_and_check_token
    @procedure = Procedure.for_api.find(params[:procedure_id])

    administrateur = find_administrateur_for_token(@procedure)
    if administrateur
      Current.administrateur = administrateur
    else
      render json: {}, status: :unauthorized
    end

    order = ORDER_DIRECTIONS.fetch(params[:order], :asc)
    @dossiers = @procedure.dossiers.state_not_brouillon.order_by_created_at(order)

  rescue ActiveRecord::RecordNotFound
    render json: {}, status: :not_found
  end
end

app/controllers/api/v2/dossiers_controller.rb
class API::V2::DossiersController < API::V2::BaseController
  before_action :ensure_dossier_present

  def pdf
    @include_infos_administration = true
    render(file: 'dossiers/show', formats: [:pdf])
  end

  def geojson
    send_data dossier.to_feature_collection.to_json,
      type: 'application/json',
      filename: "dossier-#{dossier.id}-features.json"
  end

  private

  def ensure_dossier_present
    if dossier.blank?
      head :unauthorized
    end
  end

  def dossier
    @dossier ||= GlobalID::Locator.locate_signed(params[:id].to_s, for: 'api_v2')
  end
end

app/controllers/manager/dossiers_controller.rb
module Manager
  class DossiersController < Manager::ApplicationController
    #
    # Administrate overrides
    #

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    def scoped_resource
      if unfiltered_list?
        # Don't display discarded dossiers in the unfiltered list…
        Dossier.kept
      else
        # … but allow them to be searched and displayed.
        Dossier.with_discarded
      end
    end

    #
    # Custom actions
    #

    def discard
      dossier = Dossier.find(params[:id])
      dossier.discard_and_keep_track!(current_super_admin, :manager_request)

      logger.info("Le dossier #{dossier.id} est supprimé par #{current_super_admin.email}")
      flash[:notice] = "Le dossier #{dossier.id} a été supprimé."

      redirect_to manager_dossier_path(dossier)
    end

    def restore
      dossier = Dossier.with_discarded.find(params[:id])
      dossier.restore(current_super_admin)

      flash[:notice] = "Le dossier #{dossier.id} a été restauré."

      redirect_to manager_dossier_path(dossier)
    end

    def repasser_en_instruction
      dossier = Dossier.find(params[:id])
      dossier.repasser_en_instruction(current_super_admin)

      logger.info("Le dossier #{dossier.id} est repassé en instruction par #{current_super_admin.email}")
      flash[:notice] = "Le dossier #{dossier.id} est repassé en instruction."

      redirect_to manager_dossier_path(dossier)
    end

    private

    def unfiltered_list?
      action_name == "index" && !params[:search]
    end
  end
end

app/helpers/dossier_helper.rb
module DossierHelper
  include EtablissementHelper

  def button_or_label_class(dossier)
    if dossier.accepte?
      'accepted'
    elsif dossier.sans_suite?
      'without-continuation'
    elsif dossier.refuse?
      'refused'
    end
  end

  def highlight_if_unseen_class(seen_at, updated_at)
    if updated_at.present? && seen_at&.<(updated_at)
      "highlighted"
    end
  end

  def url_for_dossier(dossier)
    if dossier.brouillon?
      brouillon_dossier_path(dossier)
    else
      dossier_path(dossier)
    end
  end

  def url_for_new_dossier(procedure)
    if procedure.brouillon?
      new_dossier_url(procedure_id: procedure.id, brouillon: true)
    else
      new_dossier_url(procedure_id: procedure.id)
    end
  end

  def dossier_form_class(dossier)
    classes = ['form']
    if autosave_available?(dossier)
      classes << 'autosave-enabled'
    end
    classes.join(' ')
  end

  def autosave_available?(dossier)
    dossier.brouillon?
  end

  def dossier_submission_is_closed?(dossier)
    dossier.brouillon? && dossier.procedure.close?
  end

  def dossier_display_state(dossier_or_state, lower: false)
    state = dossier_or_state.is_a?(Dossier) ? dossier_or_state.state : dossier_or_state
    display_state = I18n.t(state, scope: [:activerecord, :attributes, :dossier, :state])
    lower ? display_state.downcase : display_state
  end

  def dossier_legacy_state(dossier)
    case dossier.state
    when Dossier.states.fetch(:en_construction)
      'initiated'
    when Dossier.states.fetch(:en_instruction)
      'received'
    when Dossier.states.fetch(:accepte)
      'closed'
    when Dossier.states.fetch(:refuse)
      'refused'
    when Dossier.states.fetch(:sans_suite)
      'without_continuation'
    else
      dossier.state
    end
  end

  def status_badge(state)
    status_text = dossier_display_state(state, lower: true)
    status_class = state.tr('_', '-')
    tag.span(status_text, class: "label #{status_class} ")
  end

  def deletion_reason_badge(reason)
    if reason.present?
      status_text = I18n.t(reason, scope: [:activerecord, :attributes, :deleted_dossier, :reason])
      status_class = reason.tr('_', '-')
    else
      status_text = I18n.t(:unknown, scope: [:activerecord, :attributes, :deleted_dossier, :reason])
      status_class = 'unknown'
    end

    tag.span(status_text, class: "label #{status_class} ")
  end

  def demandeur_dossier(dossier)
    if dossier.procedure.for_individual?
      "#{dossier&.individual&.nom} #{dossier&.individual&.prenom}"
    else
      if dossier.etablissement.present?
        raison_sociale_or_name(dossier.etablissement)
      else
        ""
      end
    end
  end
end

app/views/shared/dossiers/_demande.html.haml
.container
  - if dossier.en_construction_at.present?
    .card
      = render partial: "shared/dossiers/infos_generales", locals: { dossier: dossier }

  .tab-title Identité du demandeur
  .card
    - if dossier.france_connect_information.present?
      = render partial: "shared/dossiers/france_connect_informations", locals: { user_information: dossier.france_connect_information }
    = render partial: "shared/dossiers/user_infos", locals: { user: dossier.user }

    - if dossier.etablissement.present?
      = render partial: "shared/dossiers/identite_entreprise", locals: { etablissement: dossier.etablissement, profile: profile }

      - if profile == 'usager' && !dossier.read_only?
        .flex.row-reverse
          = link_to "Modifier le SIRET", siret_dossier_path(dossier), class: 'button'

    - if dossier.individual.present?
      = render partial: "shared/dossiers/identite_individual", locals: { individual: dossier.individual }

      - if profile == 'usager' && !dossier.read_only?
        .flex.row-reverse
          = link_to "Modifier l'identité", identite_dossier_path(dossier), class: 'button'

  .tab-title Formulaire
  - champs = dossier.champs.includes(:type_de_champ)
  - if champs.any? || dossier.procedure.routee?
    .card
      = render partial: "shared/dossiers/champs", locals: { champs: champs, dossier: dossier, demande_seen_at: demande_seen_at, profile: profile }

app/views/shared/dossiers/_edit.html.haml
.dossier-edit.container
  = render partial: "shared/dossiers/submit_is_over", locals: { dossier: dossier }

  - if apercu
    - form_options = { url: '', method: :get }
  - elsif dossier.brouillon?
    - form_options = { url: brouillon_dossier_url(dossier), method: :patch }
  - else
    - form_options = { url: modifier_dossier_url(dossier), method: :patch }

  = form_for dossier, form_options.merge({ html: { id: 'dossier-edit-form', class: dossier_form_class(dossier), multipart: true } }) do |f|

    .prologue
      %p.mandatory-explanation
        Les champs suivis d’un astérisque (
        %span.mandatory> *
        ) sont obligatoires.
      - if dossier.brouillon?
        %p.mandatory-explanation
          - if autosave_available?(dossier)
            Votre dossier est enregistré automatiquement après chaque modification. Vous pouvez à tout moment fermer la fenêtre et reprendre plus tard là où vous en étiez.
          - else
            Pour enregistrer votre dossier et le reprendre plus tard, cliquez sur le bouton « Enregistrer le brouillon » en bas à gauche du formulaire.
      - if !apercu && dossier.france_connect_information.present?
        = render partial: "shared/dossiers/france_connect_informations", locals: { user_information: dossier.france_connect_information }
      - if notice_url(dossier.procedure).present?
        = link_to notice_url(dossier.procedure), target: '_blank', rel: 'noopener', class: 'button notice', title: "Pour vous aider à remplir votre dossier, vous pouvez consulter le guide de cette démarche." do
          %span.icon.info>
          Guide de la démarche

    %hr

    - if dossier.show_groupe_instructeur_selector?
      = f.label :groupe_instructeur_id do
        = dossier.procedure.routing_criteria_name
        %span.mandatory *
      = f.select :groupe_instructeur_id,
        dossier.procedure.groupe_instructeurs.order(:label).map { |gi| [gi.label, gi.id] },
        { include_blank: dossier.brouillon? }

    = f.fields_for :champs, dossier.champs do |champ_form|
      - champ = champ_form.object
      = render partial: "shared/dossiers/editable_champs/editable_champ",
        locals: { champ: champ, form: champ_form }

    - if !apercu
      .dossier-edit-sticky-footer
        .send-dossier-actions-bar
          - if dossier.brouillon?
            - if autosave_available?(dossier)
              = render partial: 'users/dossiers/autosave'
            - else
              = f.button 'Enregistrer le brouillon',
                formnovalidate: true,
                class: 'button send secondary',
                data: { 'disable-with': "Envoi en cours…" }

            - if dossier.can_transition_to_en_construction?
              = f.button 'Déposer le dossier',
                name: :submit_draft,
                value: true,
                class: 'button send primary',
                disabled: !current_user.owns?(dossier),
                data: { 'disable-with': "Envoi en cours…" }

          - else
            = f.button 'Enregistrer les modifications du dossier',
              class: 'button send primary',
              data: { 'disable-with': "Envoi en cours…" }

        - if dossier.brouillon? && !current_user.owns?(dossier)
          .send-notice.invite-cannot-submit
            En tant qu’invité, vous pouvez remplir ce formulaire – mais le titulaire du dossier doit le déposer lui-même.

        = render partial: "shared/dossiers/submit_is_over", locals: { dossier: dossier }

app/views/shared/dossiers/_header.html.haml
%h1
  %span.icon.folder
  = procedure_libelle(dossier.procedure)

.dossier-form-actions
  - if current_user.owns?(dossier)
    = render partial: 'invites/dropdown', locals: { dossier: dossier }

app/views/shared/dossiers/_identite_entreprise.html.haml
%table.table.vertical.dossier-champs
  %tbody
    - if etablissement.diffusable_commercialement == false && profile != 'instructeur'
      %tr
        %td= t('warning_for_private_info', etablissement: raison_sociale_or_name(etablissement), scope: 'views.shared.dossiers.identite_entreprise')
    - else
      %tr
        %th.libelle Dénomination :
        %td= raison_sociale_or_name(etablissement)
      %tr
        %th.libelle SIRET :
        %td= etablissement.siret

      - if etablissement.siret != etablissement.entreprise.siret_siege_social
        %tr
          %th.libelle SIRET du siège social:
          %td= etablissement.entreprise.siret_siege_social
      %tr
        %th.libelle Forme juridique :
        %td= sanitize(etablissement.entreprise.forme_juridique)
      %tr
        %th.libelle Libellé NAF :
        %td= etablissement.libelle_naf
      %tr
        %th.libelle Code NAF :
        %td= etablissement.naf
      %tr
        %th.libelle Date de création :
        %td= try_format_date(etablissement.entreprise.date_creation)
      - if profile == 'instructeur'
        %tr
          %th.libelle
            Effectif mensuel
            = try_format_mois_effectif(etablissement)
            (URSSAF) :
          %td= etablissement.entreprise_effectif_mensuel
        %tr
          %th.libelle
            Effectif moyen annuel
            = etablissement.entreprise_effectif_annuel_annee
            (URSSAF) :
          %td= etablissement.entreprise_effectif_annuel
      %tr
        %th.libelle Effectif de l'organisation (INSEE) :
        %td
          = effectif(etablissement)
      %tr
        %th.libelle Numéro de TVA intracommunautaire :
        %td= etablissement.entreprise.numero_tva_intracommunautaire
      %tr
        %th.libelle Adresse :
        %td
          - etablissement.adresse.split("\n").each do |line|
            = line
            %br
      %tr
        %th.libelle Capital social :
        %td= pretty_currency(etablissement.entreprise.capital_social)
      %tr
        %th.libelle Chiffre d'affaires :
        %td
          - if profile == 'instructeur'
            %details
              - etablissement.exercices.each_with_index do |exercice, index|
                = "#{exercice.date_fin_exercice.year} : "
                = pretty_currency(exercice.ca)
                %br
          - elsif etablissement.exercices.present?
            = t('activemodel.models.exercices_summary', count: etablissement.exercices.count)


      - if etablissement.entreprise_bilans_bdf.present?
        - if profile == 'instructeur'
          = render partial: 'shared/dossiers/identite_entreprise_bilan_detail',
            locals: { libelle: 'Résultat exercice', key: 'resultat_exercice', etablissement: etablissement }

          = render partial: 'shared/dossiers/identite_entreprise_bilan_detail',
            locals: { libelle: "Excédent brut d'exploitation", key: 'excedent_brut_exploitation', etablissement: etablissement }

          = render partial: 'shared/dossiers/identite_entreprise_bilan_detail',
            locals: { libelle: 'Fonds de roulement net global', key: 'fonds_roulement_net_global', etablissement: etablissement }

          = render partial: 'shared/dossiers/identite_entreprise_bilan_detail',
            locals: { libelle: 'Besoin en fonds de roulement', key: 'besoin_en_fonds_de_roulement', etablissement: etablissement }
          %tr
            %th.libelle
              Chiffres financiers clés (Banque de France)
              = "en #{pretty_currency_unit(etablissement.entreprise_bilans_bdf_monnaie)} :"

            - if controller.is_a?(Instructeurs::AvisController)
              %td
                Les consulter
                = link_to "au format csv", bilans_bdf_instructeur_avis_path(@avis, format: 'csv')
                ,
                = link_to "au format xlsx", bilans_bdf_instructeur_avis_path(@avis, format: 'xlsx')
                ou
                = link_to "au format ods", bilans_bdf_instructeur_avis_path(@avis, format: 'ods')
            - else
              %td
                Les consulter
                = link_to "au format csv", bilans_bdf_instructeur_dossier_path(procedure_id: @dossier.procedure.id, dossier_id: @dossier.id, format: 'csv')
                ,
                = link_to "au format xlsx", bilans_bdf_instructeur_dossier_path(procedure_id: @dossier.procedure.id, dossier_id: @dossier.id, format: 'xlsx')
                ou
                = link_to "au format ods", bilans_bdf_instructeur_dossier_path(procedure_id: @dossier.procedure.id, dossier_id: @dossier.id, format: 'ods')
        - else
          %tr
            %th.libelle
              Bilans Banque de France :
            %td Les 3 derniers bilans connus de votre entreprise par la Banque de France ont été joints à votre dossier.
      - if etablissement.entreprise_attestation_sociale.attached?
        %tr
          %th.libelle Attestation sociale :
          - if profile == 'instructeur'
            %td= link_to "Consulter l'attestation", url_for(etablissement.entreprise_attestation_sociale)
          - else
            %td Une attestation de vigilance délivrée par l'ACOSS a été jointe à votre dossier.

      - if etablissement.entreprise_attestation_fiscale.attached?
        %tr
          %th.libelle Attestation fiscale :
          - if profile == 'instructeur'
            %td= link_to "Consulter l'attestation", url_for(etablissement.entreprise_attestation_fiscale)
          - else
            %td Une attestation fiscale délivrée par l'URSSAF a été jointe à votre dossier.

      - if etablissement.association?
        %tr
          %th.libelle Numéro RNA :
          %td= etablissement.association_rna
        %tr
          %th.libelle Titre :
          %td= etablissement.association_titre
        %tr
          %th.libelle Objet :
          %td= etablissement.association_objet
        %tr
          %th.libelle Date de création :
          %td= try_format_date(etablissement.association_date_creation)
        %tr
          %th.libelle Date de publication :
          %td= try_format_date(etablissement.association_date_publication)
        %tr
          %th.libelle Date de déclaration :
          %td= try_format_date(etablissement.association_date_declaration)

%p
  = link_to "➡ Autres informations sur l’organisme sur « annuaire-entreprises.data.gouv.fr » (ex: fiche d'immatriculation RNCS)",
  "https://annuaire-entreprises.data.gouv.fr/entreprise/#{etablissement.siren}",
  target: "_blank"

app/views/shared/dossiers/_user_infos.html.haml
%table.table.vertical.dossier-champs
  %tbody
    %tr
      %th.libelle Email :
      %td= user.email